cmake_minimum_required(VERSION 3.20)
project(crypto_end_to_end LANGUAGES C CXX)
set(ROBOTWEAX_SRT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ROBOTWEAX_SRT_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(ROBOTWEAX_SRT_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_AEAD_API_PREVIEW ON CACHE BOOL "" FORCE)
add_subdirectory(../.. library)
add_executable(crypto_end_to_end main.cpp)
target_compile_features(crypto_end_to_end PRIVATE cxx_std_20)
target_compile_definitions(crypto_end_to_end PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN ENABLE_AEAD_API_PREVIEW)
target_link_libraries(crypto_end_to_end PRIVATE RobotweaxSRT::srt)
if(WIN32)
    target_link_libraries(crypto_end_to_end PRIVATE ws2_32)
endif()
